# Generated by Django 4.0.3 on 2022-04-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('store', '0018_orderitem_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproduct',
            name='vendor',
        ),
        migrations.AddField(
            model_name='featuredproduct',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
