# Generated by Django 3.2.5 on 2022-05-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
