# Generated by Django 3.2.5 on 2022-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_featuredproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Footware', 'Footware'), ('Bags', 'Bags'), ('Accessories', 'Accessories'), ('Eyewear', 'Eyewear'), ('Cosmetics and Beauty', 'Cosmetics and Beauty'), ('Consumer Electronics', 'Consumer Electronics'), ('Sporting goods', 'Sporting goods')], max_length=200, null=True),
        ),
    ]
