# Generated by Django 3.2.5 on 2022-08-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_brandcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='brandcategories',
            name='name',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Balenciaga', 'Balenciaga'), ('Dior', 'Dior'), ('Prada', 'Prada'), ('Vans', 'Vans'), ('Bata', 'Bata')], max_length=200, null=True),
        ),
    ]
