# Generated by Django 3.2.5 on 2022-08-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20220810_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcategories',
            name='main_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.categories'),
        ),
    ]
