# Generated by Django 3.2.5 on 2022-08-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_brandcategories_main_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMiniCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand_categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brandcategories')),
            ],
        ),
    ]
