# Generated by Django 3.2.5 on 2022-08-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_brandminicategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brandcategories'),
        ),
    ]
