# Generated by Django 3.2.5 on 2023-01-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_featuredproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mainCcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.categories'),
        ),
    ]
