# Generated by Django 3.2.5 on 2023-01-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandminicategories',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
