# Generated by Django 3.2.5 on 2023-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_brandminicategories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandminicategories',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
