# Generated by Django 3.2.5 on 2023-01-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_brandminicategories_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='mainCcategory',
            new_name='mainCategory',
        ),
    ]
