# Generated by Django 3.2.5 on 2022-06-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendRequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequests',
            old_name='state',
            new_name='friends',
        ),
    ]
