# Generated by Django 3.2.5 on 2022-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendRequest', '0002_rename_state_friendrequests_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
