# Generated by Django 3.2.5 on 2022-05-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20220504_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shop_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors'),
        ),
    ]
