# Generated by Django 3.2.5 on 2022-06-23 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_shop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='shop_name',
        ),
    ]
