# Generated by Django 3.2.5 on 2022-06-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_remove_vendor_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
